addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.21.0")
addSbtPlugin("com.github.sbt"       % "sbt-pgp"                  % "2.3.1")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.12.2")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.2")
