addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.1.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.7.1")
addSbtPlugin("com.github.sbt"       % "sbt-pgp"                  % "2.1.2")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"                  % "1.0.2")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.9.13")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.10")
